apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: scoresauce-vassast-org
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: albin.vass@gmail.com
    privateKeySecretRef:
      name: scoresauce-vinemetrics-org
    solvers:
    - http01:
        ingress:
          class: nginx

