apiVersion: v1
kind: Service
metadata:
  name: graphite-statsd
  labels:
    app: graphite-statsd
spec:
  clusterIp: None
  ports:
  - port: 8125
    name: statsd
  - port: 80
    name: http
  selector:
    app: graphite-statsd
