apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinemetrics-web
spec:
  selector:
    matchLabels:
      app: vinemetrics-web
  replicas: 1
  template:
    metadata:
      labels:
        app: vinemetrics-web
    spec:
      containers:
      - name: vinemetrics-web
        image: ghcr.io/albinvass/vinemetrics-web
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
