apiVersion: v1
kind: Service
metadata:
  name: vinemetrics-web
  labels:
    app: vinemetrics-web
spec:
  ports:
  - port: 80
    targetPort: http
    name: http
  selector:
    app: vinemetrics-web


